### PR TITLE
keep in-progress label on merge-conflict #137

### PR DESCRIPTION
**Pull request by naazy**
keep in-progress label on merge-conflict #137

### CODE REVIEW

**Comment by iteles** [comment]
Adding @danwhy and @shouston3 as potential reviewers as they've shown interest in dwylbot in the past. If you guys have some spare time during the workday, please take a look 😊

**Review by samhstn — APPROVED** [review]
Looks great. Are there tests for these?

**Comment by naazy** [comment]
@shouston3 re tests: https://github.com/dwyl/dwylbot/issues/154

**Review by samhstn — APPROVED** [review]
Nice, I think it's fine for now

**Pull request merged**
