### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### dwyl/dwylbot now has a Chat Room on Gitter

@markwilliamfirth has just created a chat room. You can visit it here: [https://gitter.im/dwyl/dwylbot](https://gitter.im/dwyl/dwylbot?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/dwyl/dwylbot?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Review by iteles — APPROVED** [review]
Might as well!

**Comment by nelsonic** [comment]
@iteles please let me know when you have time to discuss... 👍

**Comment by ghost** [comment]
@nelsonic was I not supposed to make a PR?

**Comment by nelsonic** [comment]
@markwilliamfirth it's _all_ good. 👍 
(_Gitter is our **current** "solution" for team/project communication..._) 😉

**Pull request merged**
