### PR TITLE
update documentation on how to run dwybot on your machine

### PR DESCRIPTION
**Pull request by SimonLab**
ref: #167

Add more detailed steps on how to run locally dwylbot

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
@SimonLab looks good. 👍

**Comment by rub1e** [comment]
I've got a few updates to the readme based on my experiences trying to run the dwylbot - a few things for people who don't already have the stack installed on their machine

But I'll have to finish it at home as it's flummoxing my little Chromebook so will go through the rest of the process on a real machine and update then 😸

**Review by rub1e — APPROVED** [review]
I've corrected a couple of typos and added a warning that you'll need to install Elixir/Phoenix/Postgres along with links to installation pages. 

Once all that was installed it wasn't actually that difficult, but I wasn't able to get dwylbot working properly in the end - I'll copy the debug info into a comment as I couldn't understand a bit of it. Basically it seems to work as far as recognising the app and the repo it's installed on, but it crashes when it tries to comment on an issue. I'm assuming this is a problem with me (operator error) rather than the bot.

The upshot is that I think this will be sufficient for people who've taken the time to understand Elixir/Phoenix or who've already got them installed, but it takes a while to get up and running if you don't.

**Comment by rub1e** [comment]
[info] POST /event/new
[debug] Processing by Dwylbot.EventController.new/2
  Parameters: %{"action" => "opened", "installation" => %{"id" => 79821}, "issue" => %{"assignee" => nil, "assignees" => [], "author_association" => "OWNER", "body" => "", "closed_at" => nil, "comments" => 0, "comments_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/issues/6/comments", "created_at" => "2018-01-12T09:01:15Z", "events_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/issues/6/events", "html_url" => "https://github.com/rub1e/Javascript-stopwatch/issues/6", "id" => 288049535, "labels" => [], "labels_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/issues/6/labels{/name}", "locked" => false, "milestone" => nil, "number" => 6, "repository_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch", "state" => "open", "title" => "5", "updated_at" => "2018-01-12T09:01:15Z", "url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/issues/6", "user" => %{"avatar_url" => "https://avatars0.githubusercontent.com/u/11595920?v=4", "events_url" => "https://api.github.com/users/rub1e/events{/privacy}", "followers_url" => "https://api.github.com/users/rub1e/followers", "following_url" => "https://api.github.com/users/rub1e/following{/other_user}", "gists_url" => "https://api.github.com/users/rub1e/gists{/gist_id}", "gravatar_id" => "", "html_url" => "https://github.com/rub1e", "id" => 11595920, "login" => "rub1e", "organizations_url" => "https://api.github.com/users/rub1e/orgs", "received_events_url" => "https://api.github.com/users/rub1e/received_events", "repos_url" => "https://api.github.com/users/rub1e/repos", "site_admin" => false, "starred_url" => "https://api.github.com/users/rub1e/starred{/owner}{/repo}", "subscriptions_url" => "https://api.github.com/users/rub1e/subscriptions", "type" => "User", "url" => "https://api.github.com/users/rub1e"}}, "repository" => %{"statuses_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/statuses/{sha}", "git_refs_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/git/refs{/sha}", "issue_comment_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/issues/comments{/number}", "watchers" => 2, "mirror_url" => nil, "languages_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/languages", "stargazers_count" => 2, "license" => nil, "forks" => 0, "default_branch" => "master", "comments_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/comments{/number}", "commits_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/commits{/sha}", "id" => 35757940, "clone_url" => "https://github.com/rub1e/Javascript-stopwatch.git", "homepage" => nil, "stargazers_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/stargazers", "events_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/events", "blobs_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/git/blobs{/sha}", "forks_count" => 0, "pushed_at" => "2015-05-17T15:16:31Z", "git_url" => "git://github.com/rub1e/Javascript-stopwatch.git", "hooks_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/hooks", "owner" => %{"avatar_url" => "https://avatars0.githubusercontent.com/u/11595920?v=4", "events_url" => "https://api.github.com/users/rub1e/events{/privacy}", "followers_url" => "https://api.github.com/users/rub1e/followers", "following_url" => "https://api.github.com/users/rub1e/following{/other_user}", "gists_url" => "https://api.github.com/users/rub1e/gists{/gist_id}", "gravatar_id" => "", "html_url" => "https://github.com/rub1e", "id" => 11595920, "login" => "rub1e", "organizations_url" => "https://api.github.com/users/rub1e/orgs", "received_events_url" => "https://api.github.com/users/rub1e/received_events", "repos_url" => "https://api.github.com/users/rub1e/repos", "site_admin" => false, "starred_url" => "https://api.github.com/users/rub1e/starred{/owner}{/repo}", "subscriptions_url" => "https://api.github.com/users/rub1e/subscriptions", "type" => "User", "url" => "https://api.github.com/users/rub1e"}, "trees_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/git/trees{/sha}", "git_commits_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/git/commits{/sha}", "collaborators_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/collaborators{/collaborator}", "watchers_count" => 2, "archived" => false, "tags_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/tags", "merges_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/merges", "releases_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/releases{/id}", "subscribers_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/subscribers", "ssh_url" => "git@github.com:rub1e/Javascript-stopwatch.git", "created_at" => "2015-05-17T08:22:41Z", "name" => "Javascript-stopwatch", "has_issues" => true, "private" => false, "git_tags_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/git/tags{/sha}", "has_projects" => true, "archive_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/{archive_format}{/ref}", "has_wiki" => true, "open_issues_count" => 5, "milestones_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/milestones{/number}", "forks_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/forks", "url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch", "downloads_url" => "https://api.github.com/repos/rub1e/Javascript-stopwatch/downloads", ...}, "sender" => %{"avatar_url" => "https://avatars0.githubusercontent.com/u/11595920?v=4", "events_url" => "https://api.github.com/users/rub1e/events{/privacy}", "followers_url" => "https://api.github.com/users/rub1e/followers", "following_url" => "https://api.github.com/users/rub1e/following{/other_user}", "gists_url" => "https://api.github.com/users/rub1e/gists{/gist_id}", "gravatar_id" => "", "html_url" => "https://github.com/rub1e", "id" => 11595920, "login" => "rub1e", "organizations_url" => "https://api.github.com/users/rub1e/orgs", "received_events_url" => "https://api.github.com/users/rub1e/received_events", "repos_url" => "https://api.github.com/users/rub1e/repos", "site_admin" => false, "starred_url" => "https://api.github.com/users/rub1e/starred{/owner}{/repo}", "subscriptions_url" => "https://api.github.com/users/rub1e/subscriptions", "type" => "User", "url" => "https://api.github.com/users/rub1e"}}
  Pipelines: [:api]
[info] Sent 500 in 16ms
[error] #PID<0.413.0> running Dwylbot.Endpoint terminated
Server: f3eaec69.ngrok.io:80 (http)
Request: POST /event/new
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in :jose_jwk.from_pem/1
        (jose) src/jose_jwk.erl:371: :jose_jwk.from_pem(nil)
        (jose) lib/jose/jwk.ex:161: JOSE.JWK.from_pem/1
        (dwylbot) web/controllers/github_api/http_client.ex:39: Dwylbot.GithubAPI.HTTPClient.get_installation_token/1
        (dwylbot) web/controllers/event_controller.ex:10: Dwylbot.EventController.new/2
        (dwylbot) web/controllers/event_controller.ex:1: Dwylbot.EventController.action/2
        (dwylbot) web/controllers/event_controller.ex:1: Dwylbot.EventController.phoenix_controller_pipeline/2
        (dwylbot) lib/dwylbot/endpoint.ex:1: Dwylbot.Endpoint.instrument/4
        (dwylbot) lib/phoenix/router.ex:261: Dwylbot.Router.dispatch/2
        (dwylbot) web/router.ex:1: Dwylbot.Router.do_call/2
        (dwylbot) lib/dwylbot/endpoint.ex:1: Dwylbot.Endpoint.phoenix_pipeline/1
        (dwylbot) lib/plug/debugger.ex:123: Dwylbot.Endpoint."call (overridable 3)"/2
        (dwylbot) lib/dwylbot/endpoint.ex:1: Dwylbot.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /home/rubie/dwylbot/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

**Review by iteles — APPROVED** [review]
Thanks for the updates @SimonLab and the tweaks @rub1e ! 👍

**Comment by SimonLab** [comment]
@rub1e the error is due to a missing environment variable when your ran the project: https://github.com/dwyl/dwylbot/blob/6552a25898fa8590b9c9380d18453e5527024827/web/controllers/github_api/http_client.ex#L37-L39

The ```PRIVATRE_APP_KEY``` is used to:
- authenticate dwylbot Github App
- then once authenticated to ask more information about specific dwylbot installations and especially to get tokens linked to the installations. this allow dwylbot to add comments to the repos: https://github.com/dwyl/dwylbot/blob/6552a25898fa8590b9c9380d18453e5527024827/web/controllers/event_controller.ex#L10

see also the Github doc: https://developer.github.com/apps/building-github-apps/authentication-options-for-github-apps/#authenticating-as-an-installation

You might have missed (skipped?!) some steps on our doc: https://github.com/dwyl/dwylbot#run-a-dwylbot-server or maybe it's not clear enough yet?

Thanks for the updates on the Readme

**Comment by rub1e** [comment]
@SimonLab it's possible, as I did have trouble with the environmental variables, but I thought I'd got it working (I think I ended up just putting them in a file manually). Either way, glad it's sorted!

**Pull request merged**
