### PR TITLE
Filling in the Gaps in Documentation

### PR DESCRIPTION
**Pull request by nelsonic**
Adds Documentation 📝 
and GitHub Auth. ✅

### CODE REVIEW

**Comment by iteles** [comment]
@nelsonic When this PR is done and reviewed, I would like to add it to https://github.com/dwyl/contributing as an answer to https://github.com/dwyl/contributing/issues/69 👍

**Comment by nelsonic** [comment]
@iteles the "quest" in documenting is quite simple: to help the `next` person `continue` the work.
If the `next` person cannot simply ["_take the torch_"](https://www.usingenglish.com/reference/idioms/take+up+the+torch.html) and keep running then we _fail_. 😞 

@SimonLab has done a _superb_ job of the "Spike" to get the GitHub Webhook working. 🎉 
And I know he has to do client work this week so I'm filling in the gaps. 😉

**Comment by SimonLab** [comment]
Sorry I will add more doc especially how I think we should build the main architecture of the DwylBot, I am still learning concurrency processes which I think will help to build the next steps

**Comment by nelsonic** [comment]
@SimonLab [don't worry](https://youtu.be/d-diB65scQU), focus on https://github.com/research-resource 😉

**Comment by iteles** [comment]
@SimonLab This definitely isn't a criticism, no one expects detailed docs with a spike! Would be good to document your learning as you go though so others can benefit from what you learnt  :blush:

**Comment by nelsonic** [comment]
image

**Comment by nelsonic** [comment]
dwyl-heart-robot-logo

_Question_ is: _what is @dwylbot's **theme tune**...?_ 🎵 
+ "computer love": https://youtu.be/ZtWTUt2RZh0
+ "love machine": https://youtu.be/owJHNSF9bm0
+ "digital love": https://youtu.be/FxzBvqY5PP0
+ "technologic": https://youtu.be/D8K90hX4PrE 
+ "robot friend": https://youtu.be/HAIDqt2aUek

**Comment by nelsonic** [comment]
Added ***GitHub Auth*** for https://github.com/dwyl/dwylbot/issues/29

image

image

Thanks to @jruts's fine work: https://github.com/jruts/playwith_phoenix/commit/173afbd7e375b023e5ed28d39cbe948594cda7ae ❤️

**Comment by jruts** [comment]
@nelsonic you're welcome :)

**Comment by nelsonic** [comment]
@jrans https://youtu.be/79DijItQXMM ? 😜

**Comment by nelsonic** [comment]
@SimonLab I did not get as far as I wanted with this PR... 😞 
but I have to go back to my work now and don't know when I will be able to continue with `dwylbot`...
Please review the PR and merge if ok so others can benefit from the Docs. thanks!

**Review by SimonLab — APPROVED** [review]
Looks great, thanks a lot @nelsonic for adding the documentation and Github auth :+1:

**Comment by nelsonic** [comment]
@SimonLab thanks for reviewing/merging. ❤️  ✅

**Pull request merged**
